// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBncqwbOh4BvYmenaFhnfYr2wFybmLXxnk',
    appId: '1:310553572677:web:d46c31b10a1c07cab0ba2c',
    messagingSenderId: '310553572677',
    projectId: 'streamer-abe89',
    authDomain: 'streamer-abe89.firebaseapp.com',
    storageBucket: 'streamer-abe89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZor_hk04xjYT-s7fsq9LY7n-wBEE_PWo',
    appId: '1:310553572677:android:f5bc4aed576da7ddb0ba2c',
    messagingSenderId: '310553572677',
    projectId: 'streamer-abe89',
    storageBucket: 'streamer-abe89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0l84SRiLOehanbYTiXUfNJOF9lkorhiE',
    appId: '1:310553572677:ios:ffa7f6ce73c71432b0ba2c',
    messagingSenderId: '310553572677',
    projectId: 'streamer-abe89',
    storageBucket: 'streamer-abe89.appspot.com',
    iosBundleId: 'com.example.streamer',
  );
}
